### PR TITLE
Transport: Do not try to pause/resume Consumers if AwaitQueue is closed

### LINKED ISSUE #206: Infinite loop with awaitQueue, out of memory (Critical) [Client]
### Your environment

- Operating system: N/a
- Browser version: N/a
- npm version: N/a
- mediasoup version: N/a
- mediasoup-client version: 3.6.51

### Issue description

The bug only exists in 3.6.51 and is a critical and is more likely to occur on slower devices. The following codepaths ignore all errors and do not properly account for the awaitQueue being closed before enqueuing again. 

https://github.com/versatica/mediasoup-client/blob/v3/src/Transport.ts#L920
https://github.com/versatica/mediasoup-client/blob/v3/src/Transport.ts#L950

The minimal code to replicate this is unfortunately an application of sufficient size to create enough load on the microtask queue, however the issue can be synthetically created by closing the awaitQueue before the finally(() => {}) block has an attempt to run. 

Flow: 
It is possible that before the awaitQueue executes the pushed executor a transport.close() event occurs which terminates the awaitQueue synchronously. When the microtask queue kicks off the executor it is immediately rejected as being closed. Since there is no handling of this event in the catch it will happily drop into the finally block. This results in the [**finally**](https://github.com/versatica/mediasoup-client/blob/v3/src/Transport.ts#L951-L960) indefinitely enqueuing the resume executor. It indefinitely increases the stack through the microtask queue, preventing a stack overflow as well. 

This will eventually eat up the clients entire allocated RAM and crash the environment it's executing in. 

Adding a console.error to the catch (and adding a bail out after 10k attempts) allows you to catch the entire stack.

    InvalidStateError: AwaitQueue closed
        at AwaitQueue.close (webpack-internal:///./node_modules/awaitqueue/lib/index.js:44:32)
        at Transport.close (webpack-internal:///./node_modules/mediasoup-client-next/lib/Transport.js:290:22)
        at Wrapper.eval (webpack-internal:///./<snip>:608:50)
        at executeAction (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:246:19)
        at Wrapper.res (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:238:16)
        at Wrapper.eval (webpack-internal:///<snip>:160:17)
        at Generator.next (<anonymous>)
        at Wrapper.eval [as <snip>] (webpack-internal:///<snip>:196:24)
        at <snip> (webpack-internal:///<snip>:270:14)
        at <snip> [as onClick] (webpack-internal:///<snip>:49:39)
        at eval (webpack-internal:///<snip>:96:141)
    From previous event:
        at AwaitQueue.eval (webpack-internal:///./node_modules/awaitqueue/lib/index.js:68:20)
        at Generator.next (<anonymous>)
        at eval (webpack-internal:///./node_modules/awaitqueue/lib/index.js:8:71)
    From previous event:
        at __awaiter (webpack-internal:///./node_modules/awaitqueue/lib/index.js:4:12)
        at AwaitQueue.push (webpack-internal:///./node_modules/awaitqueue/lib/index.js:57:16)
        at Transport._resumePendingConsumers (webpack-internal:///./node_modules/mediasoup-client-next/lib/Transport.js:763:22)
        at Proxy.eval (webpack-internal:///./node_modules/mediasoup-client-next/lib/Transport.js:885:14)
        at Proxy.emit (webpack-internal:///./node_modules/events/events.js:146:5)
        at Proxy.resume (webpack-internal:///./node_modules/mediasoup-client-next/lib/Consumer.js:243:10)
        at eval (webpack-internal:///<snip>:194:185)
        at Array.forEach (<anonymous>)
        at <snip>.fireImmediately (webpack-internal:///<snip>:191:25)
        at executeAction (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:246:19)
        at res (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:238:16)
        at reactionRunner (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:665:13)
        at Reaction.eval [as onInvalidate] (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:645:13)
        at Reaction.runReaction (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:3511:26)
        at runReactionsHelper (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:3637:35)
        at reactionScheduler (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:3615:47)
        at eval (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:3644:71)
        at batchedUpdates$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:21888:12)
        at reactionScheduler (webpack-internal:///./node_modules/mobx/lib/mobx.module.js:3644:47)

### PR DESCRIPTION
**Pull request by jmillan**
Fixes #206

### CODE REVIEW

File: src/Transport.ts [hunk 1]
```diff
@@ -912,22 +912,30 @@ export class Transport extends EnhancedEventEmitter
...
-				);
+				try
+				{
+					await this._handler.pauseReceiving(
+						pendingPauseConsumers.map((consumer) => consumer.localId)
+					);
+				}
+				catch (error)
+				{
+					logger.error('_pausePendingConsumers() | failed to pause Consumers', error);
```
Comment (ibc) [inline src/Transport.ts]: ":" at the end of the string?

File: src/Transport.ts [hunk 2]
```diff
@@ -942,13 +950,19 @@ export class Transport extends EnhancedEventEmitter
...
-				);
+				try
+				{
+					await this._handler.resumeReceiving(
+						pendingResumeConsumers.map((consumer) => consumer.localId)
+					);
+				}
+				catch (error)
+				{
+					logger.error('_resumePendingConsumers() | failed to resume Consumers', error);
```
Comment (ibc) [inline src/Transport.ts]: Same

**Review by ibc — APPROVED** [review]

File: src/Transport.ts (hunk 1 above)
Comment (jmillan) [reply src/Transport.ts]: wow, true
